dist: xenial
language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
install:
  - "pip install -U pip"
  - "pip install pipenv"
  - "pipenv install"
script:
  - "pipenv run coverage run src/manage.py test"
  - "pipenv run coverage report"
  - "coveralls"
  - "pipenv run flake8 src/ --exclude=src/call_api/wsgi.py,**/migrations/**"