# Generated by Django 2.2.2 on 2019-06-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.PositiveIntegerField()),
                ('record_type', models.CharField(choices=[('start', 'Start'), ('end', 'End')], max_length=5, verbose_name='Record Type')),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(blank=True, max_length=11, null=True)),
                ('destination', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'verbose_name': 'Call Record',
                'verbose_name_plural': 'Call Records',
                'unique_together': {('record_type', 'call_id')},
            },
        ),
    ]
